models:
  # in order of priority
  - claude-3-5-sonnet-20240620
  - o1-preview
  - gpt-4o-2024-11-20
  - gpt-3.5-turbo-0125
pricing:
  # USD per 1M tokens
  claude-3-5-sonnet-20240620:
    input_price: 3
    output_price: 15
  o1-preview:
    input_price: 15
    output_price: 60
  gpt-4o-2024-11-20:
    input_price: 2.5
    output_price: 10
  gpt-3.5-turbo-0125:
    input_price: 0.5
    output_price: 1.5
gpt_params:
  # https://platform.openai.com/docs/api-reference/chat/create#completions/create-echo
  logprobs: true
  max_tokens: null
  seed: 123
