models:
  - gpt-4-1106-preview
  - gpt-3.5-turbo-1106
pricing:
  gpt-4-1106-preview:
    input_cost_usd_per_1K_tokens: 0.01
    output_cost_usd_per_1K_tokens: 0.03
  gpt-3.5-turbo-1106:
    input_cost_usd_per_1K_tokens: 0.0010
    output_cost_usd_per_1K_tokens: 0.0020
